### ISSUE TITLE
squaring doesn't seem to work

### ISSUE THREAD

**Issue by twiecki** [bambinos/formulae#4]
I tried `y ~ x**2` but it seemed like the squaring was ignored.

**Comment by tomicapretto** [comment]
Hi @twiecki, you are right. If you want to square a variable you have to do `y ~ I(x **2)` or, using an alternative syntax, `y ~ {x ** 2}`. This is because `**` is a valid operator for a set of terms.

For example, `(a + b + c) ** 2` is equivalent to `a + b + c + a:b + a:c + b:c`.

**PS**: This is the same logic behind the addition between terms. If you want a term that is the sum of other two terms, you do `I(x + y)` or `{x + y}` instead of just `x + y` because the latter means you want to include `x` and `y` as separated terms.

**Comment by tomicapretto** [comment]
We don't have it documented yet, but you can find it in Patsy docs [here](https://patsy.readthedocs.io/en/latest/formulas.html#operators)

**Comment by twiecki** [comment]
Maybe a warning could be displayed if someone is doing `x**2` as that
doesn't seem to make sense for a single variable.

**Comment by tomicapretto** [comment]
Added warning in #13
