### ISSUE TITLE
Correlated Random Effects 

### ISSUE THREAD

**Issue by huangziwei** [bambinos/formulae#55]
Hi. 

In [Ch3](https://stat.ethz.ch/~maechler/MEMo-pages/lMMwR.pdf) of the lme4 book manuscript, Bates showed two cases of random effects, one is correlated and the other is uncorrelated (independent):

<img width="639" alt="Screen Shot 2021-11-19 at 16 01 07" src="https://user-images.githubusercontent.com/3627182/142643914-c33dffbd-4bb0-4125-ad16-e29eac167516.png">

The correlated one is from formula `Reaction ~ 1 + Days + (1 + Days | Subject)`, the uncorrelated on is from `Reaction ~ 1 + Days + (1|Subject) + (0 + Days|Subject)`.

I tried the same formulae with `formulae`, the two design matrices are the same:

<img width="881" alt="Screen Shot 2021-11-19 at 16 04 12" src="https://user-images.githubusercontent.com/3627182/142644412-fd114336-b5c0-4b6d-a524-9bd25cd2de3e.png">

```
from formulae import design_matrices
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

data = pd.read_csv('../datasets/sleepstudy.csv')

f1 = 'Reaction ~ 1 + Days + (1 + Days | Subject)'
f2 = 'Reaction ~ 1 + Days + (1|Subject) + (0 + Days|Subject)'

fig, ax = plt.subplots(2, 1, figsize=(12, 6))
for i, formula in enumerate([f1, f2]):
    
    dm = design_matrices(formula, data)
    terms = dm.group.terms_info.keys()

    Zs = [dm.group[key] for key in dm.group.terms_info.keys()]
    Z = np.hstack(Zs)
    Z[Z ==0] = np.nan
    ax[i].imshow(Z.T)
    ax[i].set_title(formula)
```

Is this an intended behavior for `formulae` or is it a bug?

**Comment by tomicapretto** [comment]
Hi @huangziwei 

In formulae both `(1 + Days | Subject)` and `(1|Subject) + (0 + Days|Subject)` are equivalent. The resulting matrix does not determine whether the effects are modeled as correlated or not.  It's up to you to decide how to model those effects. 

In fact, both matrices obtained in lme4 contain the same information, they have the columns ordered/grouped in a different way. I think lme4 makes this distinction because of efficiency reasons. 

I have [this blogpost](https://tcapretto.netlify.app/post/2021-06-08-group-specific-effects-matrix/) where I compare results obtained with lme4 and formulae.

Also, if you have a case where this could be a problem, just let me know and we can discuss more here :)

**Comment by huangziwei** [comment]
Hi @tomicapretto,

Thanks for the quick clarification. I am still trying to understand how the correlation between random effects are computed but the lme4 book doesn't explain it very well.

**Comment by tomicapretto** [comment]
The difference is in the covariance matrix used for the random effects. When you assume they're independent, the covariance matrix is diagonal. When you say they're not independent, covariance matrix is not diagonal. I think the book you mention uses the same notation for both diagonal/non-diagonal covariance matrices. But that's because derivations are general so they apply to both cases.

**Comment by huangziwei** [comment]
Thanks a lot!
